### ISSUE TITLE
CANT DOWNLOAD

### ISSUE THREAD

**Issue by Flonixcorn** [DesktopGooseUnofficial/launcher#138] opened 2020-10-03 14:32 UTC
When I try to download the file it wont work the beta one downloads, but doesnt start.

**Comment by Vukky123** [comment] 2020-10-03 18:35
This is a duplicate of #132, which has been fixed. However, RHL 2.0 (Beta 2) hasn't launched yet.

**Closed by Vukky123** 2020-10-03 18:35 UTC
Labels: bug, duplicate
