### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by midimonster** [DesktopGooseUnofficial/launcher#134] opened 2020-08-05 00:39 UTC
Windows 10 pro
Launcher v2.0
So, i keep getting this error: (download link) https://www.mediafire.com/file/93ktwblqa7ea3az/2020-08-04+18-07-56.mkv/file
And i always am connected to the internet.

**Comment by Vukky123** [comment] 2020-08-05 04:58
duplicate of #132

**Closed by Vukky123** 2020-08-05 04:58 UTC
Labels: bug
